#version 450

// Source : https://github.com/WindyDarian/Vulkan-Forward-Plus-Renderer/blob/master/src/shaders/light_culling.comp.glsl

#include "lighting.h"
#include "common.glsl"

layout(push_constant) uniform TileInfo
{
	ivec2 viewportSize;
	ivec2 tileNums;
} tileInfo;

layout(binding = 1) writeonly buffer TileLightVisiblities
{
    LightVisiblity light_visiblities[];
};

layout(binding = 2) uniform sampler2DMS depthBuffer;

layout(binding = 3) uniform LightInfo lightInfo;

// vulkan ndc, minDepth = 0.0, maxDepth = 1.0
const vec2 ndc_upper_left = vec2(-1.0, -1.0);
const float ndc_near_plane = 0.0;
const float ndc_far_plane = 1.0;

struct ViewFrustum
{
	vec4 planes[6];
	vec3 points[8]; // 0-3 near 4-7 far
};

shared ViewFrustum frustum;
shared uint light_count_for_tile;
shared float min_depth;
shared float max_depth;

// Construct view frustum
ViewFrustum createFrustum(ivec2 tile_id)
{
	mat4 inv_projview = inverse(camera.proj * camera.view);

	vec2 ndc_size_per_tile = 2.0 * vec2(TILE_SIZE, TILE_SIZE) / tileInfo.viewportSize;

	vec2 ndc_pts[4];  // corners of tile in ndc
	ndc_pts[0] = ndc_upper_left + tile_id * ndc_size_per_tile;  // upper left
	ndc_pts[1] = vec2(ndc_pts[0].x + ndc_size_per_tile.x, ndc_pts[0].y); // upper right
	ndc_pts[2] = ndc_pts[0] + ndc_size_per_tile;
	ndc_pts[3] = vec2(ndc_pts[0].x, ndc_pts[0].y + ndc_size_per_tile.y); // lower left

	ViewFrustum frustum;

	vec4 temp;
	for (int i = 0; i < 4; i++)
	{
		temp = inv_projview * vec4(ndc_pts[i], min_depth, 1.0);
		frustum.points[i] = temp.xyz / temp.w;
		temp = inv_projview * vec4(ndc_pts[i], max_depth, 1.0);
		frustum.points[i + 4] = temp.xyz / temp.w;
	}

	vec3 temp_normal;
	for (int i = 0; i < 4; i++)
	{
		//Cax+Cby+Ccz+Cd = 0, planes[i] = (Ca, Cb, Cc, Cd)
		// temp_normal: normal without normalization
		temp_normal = cross(frustum.points[i] - camera.pos, frustum.points[i + 1] - camera.pos);
		temp_normal = normalize(temp_normal);
		frustum.planes[i] = vec4(temp_normal, - dot(temp_normal, frustum.points[i]));
	}
	// near plane
	{
		temp_normal = cross(frustum.points[1] - frustum.points[0], frustum.points[3] - frustum.points[0]);
		temp_normal = normalize(temp_normal);
		frustum.planes[4] = vec4(temp_normal, - dot(temp_normal, frustum.points[0]));
	}
	// far plane
	{
		temp_normal = cross(frustum.points[7] - frustum.points[4], frustum.points[5] - frustum.points[4]);
		temp_normal = normalize(temp_normal);
		frustum.planes[5] = vec4(temp_normal, - dot(temp_normal, frustum.points[4]));
	}

	return frustum;
}

bool isCollided(Light light, ViewFrustum frustum)
{
	bool result = true;

    // Step1: sphere-plane test
	for (int i = 0; i < 6; i++)
	{
		if (dot(light.position.xyz, frustum.planes[i].xyz) + frustum.planes[i].w  < - light.direction.w)
		{
			result = false;
			break;
		}
	}

    if (!result)
    {
        return false;
    }

    // Step2: bbox corner test (to reduce false positive)
    vec3 light_bbox_max = light.position.xyz + vec3(light.direction.w);
    vec3 light_bbox_min = light.position.xyz - vec3(light.direction.w);
    int probe;
    probe=0; for( int i=0; i<8; i++ ) probe += ((frustum.points[i].x > light_bbox_max.x)?1:0); if( probe==8 ) return false;
    probe=0; for( int i=0; i<8; i++ ) probe += ((frustum.points[i].x < light_bbox_min.x)?1:0); if( probe==8 ) return false;
    probe=0; for( int i=0; i<8; i++ ) probe += ((frustum.points[i].y > light_bbox_max.y)?1:0); if( probe==8 ) return false;
    probe=0; for( int i=0; i<8; i++ ) probe += ((frustum.points[i].y < light_bbox_min.y)?1:0); if( probe==8 ) return false;
    probe=0; for( int i=0; i<8; i++ ) probe += ((frustum.points[i].z > light_bbox_max.z)?1:0); if( probe==8 ) return false;
    probe=0; for( int i=0; i<8; i++ ) probe += ((frustum.points[i].z < light_bbox_min.z)?1:0); if( probe==8 ) return false;

	return true;
}

layout (local_size_x = 1, local_size_y = 1) in;
void main()
{
	ivec2 tileId = ivec2(gl_WorkGroupID.xy);
	uint tileIndex = tileId.y * tileInfo.tileNums.x + tileId.x;

	if (gl_LocalInvocationIndex == 0)
	{
		min_depth = 1.0;
		max_depth = 0.0;

		for (int y = 0; y < TILE_SIZE; y++)
		{
			for (int x = 0; x < TILE_SIZE; x++)
			{
				ivec2 sample_loc = ivec2(TILE_SIZE, TILE_SIZE) * tileId + ivec2(x, y);
				float pre_depth = texelFetch(depthBuffer, sample_loc, 0).x;
				min_depth = min(min_depth, pre_depth);
				max_depth = max(max_depth, pre_depth); //TODO: parallize this
			}
		}

		if (min_depth >= max_depth)
		{
			min_depth = max_depth;
		}

		frustum = createFrustum(tileId);
		light_count_for_tile = 0;
	}

	for (uint i = 0; i < lightInfo.count && light_count_for_tile < MAX_POINT_LIGHT_PER_TILE; ++i)
	{
		if (isCollided(lightInfo.lights[i], frustum))
		{
			uint slot = atomicAdd(light_count_for_tile, 1);
			if (slot >= MAX_POINT_LIGHT_PER_TILE) 
				break;
			light_visiblities[tileIndex].lightIndices[slot] = i;
		}
	}

	if (gl_LocalInvocationIndex == 0)
	{
		light_visiblities[tileIndex].count = light_count_for_tile;
	}
}