#version 450

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

struct DrawIndexedIndirectCommand
{
    uint indexCount;
    uint instanceCount;
    uint firstIndex;
    int vertexOffset;
    uint firstInstance;
};

layout(push_constant) uniform PushConstants
{
    uint drawCommandCount;
} pc;

layout(set = 0, binding = 0) buffer DrawCommands { DrawIndexedIndirectCommand commands[]; };

void main()
{
    uint index = gl_GlobalInvocationID.x;
    if (index < pc.drawCommandCount)
    {
        commands[index].instanceCount = 0;
    }
}